create table if not exists public.consultations (
  id bigint generated by default as identity primary key,
  consultation_no text unique not null,
  title text not null,
  category text,
  content text not null,
  password_hash text not null,
  answer text,
  status text not null default '접수',
  created_at timestamptz not null default now(),
  answered_at timestamptz
);

alter table public.consultations enable row level security;

drop policy if exists "anonymous insert" on public.consultations;
create policy "anonymous insert"
on public.consultations
for insert
to anon
with check (true);

drop policy if exists "admin all" on public.consultations;
create policy "admin all"
on public.consultations
for all
to authenticated
using (true)
with check (true);

create or replace function public.get_consultation(
  p_no text,
  p_password_hash text
)
returns table (
  title text,
  content text,
  answer text,
  status text,
  created_at timestamptz,
  answered_at timestamptz
)
language sql
security definer
set search_path = public
as $$
  select c.title, c.content, c.answer, c.status, c.created_at, c.answered_at
  from public.consultations c
  where c.consultation_no = p_no
    and c.password_hash = p_password_hash
  limit 1;
$$;

revoke all on function public.get_consultation(text,text) from public;
grant execute on function public.get_consultation(text,text) to anon, authenticated;